# **00. PyTorch Fundamentals Exercises**

### **1. Documentation reading**

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### **2. Create a random tensor with shape `(7, 7)`.**


In [11]:
# Import torch
import torch 

# Create random tensor
x = torch.rand(size=(7,7))
x, x.shape

(tensor([[0.6508, 0.2872, 0.4210, 0.0177, 0.1742, 0.0400, 0.0053],
         [0.9481, 0.0251, 0.3074, 0.1941, 0.6461, 0.6080, 0.2815],
         [0.5976, 0.9988, 0.0918, 0.9993, 0.2317, 0.6653, 0.6932],
         [0.4879, 0.7002, 0.8054, 0.4899, 0.6849, 0.9296, 0.4618],
         [0.7236, 0.2987, 0.9719, 0.3752, 0.1020, 0.6524, 0.4995],
         [0.2093, 0.3011, 0.7436, 0.8305, 0.0227, 0.6892, 0.0534],
         [0.3814, 0.0896, 0.4640, 0.1439, 0.0339, 0.9596, 0.3934]]),
 torch.Size([7, 7]))

### **3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).**

In [ ]:
# Create another random tensor
y = torch.rand(size=(1,7))
print(y) 
# Perform matrix multiplication 
matmul = x @ y.T  
matmul

tensor([[0.9913, 0.4260, 0.5809, 0.4125, 0.9808, 0.8076, 0.5847]])


tensor([[1.2256],
        [2.4985],
        [2.6533],
        [3.1444],
        [2.4828],
        [1.7204],
        [1.7834]])

In [ ]:
# or we can use :

matmul = torch.matmul(x, torch.transpose(y, 0, 1)) # change dim 0 to 1 
matmul

tensor([[1.2256],
        [2.4985],
        [2.6533],
        [3.1444],
        [2.4828],
        [1.7204],
        [1.7834]])

### **4. Set the random seed to `0` and do 2 & 3 over again.**

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [19]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
x = torch.rand(size=(7,7))
y = torch.rand(size=(1,7))

# Matrix multiply tensors
matmul = x @ y.T
matmul , matmul.shape 

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### **5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)**
  * If there is, set the GPU random seed to `1234`.

In [20]:
# Set random seed on the GPU

torch.cuda.manual_seed(1234)


### **6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:**

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [28]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)
# Create two random tensors on GPU
random_tensor_1 = torch.rand(size=(2,3)).to(device)
random_tensor_2 = torch.rand(size=(2,3)).to(device)
random_tensor_1, random_tensor_2

cpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))

<p align="center">
  <img src="../images/Random-on-GPU.png" width="700">
</p>


### **7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).**

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [30]:
# Perform matmul on tensor_A and tensor_B
random_tensor_1.shape , random_tensor_2.shape

tensor_C = random_tensor_1 @ random_tensor_2.T 
tensor_C, tensor_C.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]),
 torch.Size([2, 2]))

<p align="center">
  <img src="../images/matmul.png" width="700">
</p>

### **8. Find the maximum and minimum values of the output of 7.**

In [ ]:
# Find max
print("max :", torch.max(tensor_C).item())
# Find min
print("min :", torch.min(tensor_C).item())

max : 0.5617256760597229
min : 0.3647301495075226


### **9. Find the maximum and minimum index values of the output of 7.**

In [36]:
# Find arg max
print("Max index :", torch.argmax(tensor_C).item())

# Find arg min
print("Min index :", torch.argmin(tensor_C).item())

Max index : 3
Min index : 0


<p align="center">
  <img src="../images/Min-Max.png" width="700">
</p>


### **10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.**

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [44]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_D = torch.rand(size=((1, 1, 1, 10)))

# Remove single dimensions
tensor_E = torch.squeeze(tensor_D)


# Print out tensors and their shapes
print(tensor_D, tensor_D.shape)
print()
print(tensor_E, tensor_E.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
